#person:
#  name: wt
#  age: 22
#  maps: {k1: v1, k2: v2}
#  dog:
#    name: my_dog
#    age: 2
#server:
#  port: 8081
#spring:
#  profiles:
#    active: dev
#debug: true
#---
#server:
#  port: 8082
#spring:
#  profiles: dev
#---
#server:
#  port: 8083
#spring:
spring:
  datasource:
    username: root #  profiles: prod
    password: 0420
    url: jdbc:mysql://xiaom.xin:3306/enda
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall
  jpa:
    hibernate:
      # 更新或创建数据表结构
      ddl-auto: update
      # 控制台显示sql
    show-sql: true

